"""SQL backend. Books use Session; Job tables are JSON blob rows."""

from __future__ import annotations

import json
import re
import threading
from collections.abc import Iterator, Mapping, Sequence
from contextlib import contextmanager
from datetime import datetime
from typing import Any

from sqlalchemy.orm import sessionmaker

from ._common import check_collection, coerce_id, copy_record, matches, sort_records
from .backend import DatabaseBackend, RecordStore
from .errors import BackendError

_IDENT = re.compile(r"^[A-Za-z][A-Za-z0-9_]*$")


class SqlBackend(DatabaseBackend):
    def __init__(self, engine) -> None:
        self.engine = engine
        self._sessions = sessionmaker(bind=engine, expire_on_commit=False)
        self._lock = threading.RLock()
        self._tx_depth = 0
        self._tx = None
        self.ensure()

    @contextmanager
    def session(self) -> Iterator[Any]:
        item = self._sessions()
        try:
            yield item
        finally:
            item.close()

    def ensure(self) -> None:
        return

    def records(self, name: str, **_spec: Any) -> RecordStore:
        table = table_name(check_collection(name))
        with self._lock:
            self._ensure_blob_table(table)
        return _SqlStore(self, table)

    @contextmanager
    def transaction(self) -> Iterator[None]:
        with self._lock:
            if self._tx_depth == 0:
                self._tx = self.engine.connect()
                self._tx.begin()
            self._tx_depth += 1
            try:
                yield
                if self._tx_depth == 1:
                    self._tx.commit()
            except Exception:
                if self._tx_depth == 1:
                    self._tx.rollback()
                raise
            finally:
                self._tx_depth -= 1
                if self._tx_depth == 0:
                    self._tx.close()
                    self._tx = None

    def close(self) -> None:
        self.engine.dispose()

    def _execute(self, statement: str, params: Sequence[Any] = ()) -> _Result:
        if self.engine.dialect.name == "postgresql":
            statement = statement.replace("?", "%s")
        if self._tx is not None:
            result = self._tx.exec_driver_sql(statement, tuple(params))
            return _Result(result)
        with self.engine.begin() as conn:
            return _Result(conn.exec_driver_sql(statement, tuple(params)))

    def _ensure_blob_table(self, table: str) -> None:
        identity = (
            "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
            if self.engine.dialect.name == "postgresql"
            else "id INTEGER PRIMARY KEY AUTOINCREMENT"
        )
        try:
            self._execute(
                f"CREATE TABLE IF NOT EXISTS {table} "
                f"({identity}, status TEXT, created_at TEXT, data TEXT NOT NULL)"
            )
            self._execute(
                f"CREATE INDEX IF NOT EXISTS ix_{table}_claim ON {table} (status, created_at)"
            )
        except Exception as exc:
            raise BackendError(f"failed to prepare table {table}") from exc


class _SqlStore(RecordStore):
    def __init__(self, backend: SqlBackend, table: str) -> None:
        self._backend = backend
        self._table = table

    def insert(self, record: Mapping[str, Any]) -> dict[str, Any]:
        data = copy_record(record)
        with self._backend._lock:
            record_id = coerce_id(data.get("id"))
            try:
                if record_id is None:
                    data["id"] = self._insert_new(data)
                else:
                    self._backend._execute(
                        f"INSERT INTO {self._table} (id, status, created_at, data) "
                        "VALUES (?, ?, ?, ?)",
                        (record_id, data.get("status"), data.get("created_at"), _dump(data)),
                    )
            except Exception as exc:
                raise BackendError(f"duplicate id {data.get('id')}") from exc
            return copy_record(data)

    def get(self, id: int) -> dict[str, Any] | None:
        with self._backend._lock:
            row = self._backend._execute(
                f"SELECT data FROM {self._table} WHERE id = ?", (id,)
            ).fetchone()
        if row is None:
            return None
        return json.loads(row[0])

    def replace(self, id: int, record: Mapping[str, Any]) -> dict[str, Any]:
        data = copy_record(record)
        data["id"] = id
        with self._backend._lock:
            result = self._backend._execute(
                f"UPDATE {self._table} SET status = ?, created_at = ?, data = ? WHERE id = ?",
                (data.get("status"), data.get("created_at"), _dump(data), id),
            )
            if result.rowcount == 0:
                raise BackendError(f"missing id {id}")
        return copy_record(data)

    def delete(self, id: int) -> bool:
        with self._backend._lock:
            result = self._backend._execute(
                f"DELETE FROM {self._table} WHERE id = ?", (id,)
            )
            return result.rowcount > 0

    def find(
        self,
        *,
        status: str | None = None,
        eq: Mapping[str, Any] | None = None,
    ) -> list[dict[str, Any]]:
        with self._backend._lock:
            if status is None:
                rows = self._backend._execute(f"SELECT data FROM {self._table}").fetchall()
            else:
                rows = self._backend._execute(
                    f"SELECT data FROM {self._table} WHERE status = ?", (status,)
                ).fetchall()
            records = [json.loads(row[0]) for row in rows]
        if eq:
            records = [record for record in records if matches(record, eq)]
        return sort_records(records)

    def compare_and_set(
        self,
        id: int,
        *,
        field: str,
        expect: Any,
        update: Mapping[str, Any],
    ) -> dict[str, Any] | None:
        with self._backend._lock:
            current = self.get(id)
            if current is None or current.get(field) != expect:
                return None
            merged = copy_record(current)
            merged.update(update)
            merged["id"] = id
            try:
                return self.replace(id, merged)
            except BackendError:
                return None

    def _insert_new(self, data: dict[str, Any]) -> int:
        params = [data.get("status"), data.get("created_at"), _dump(data)]
        sql = f"INSERT INTO {self._table} (status, created_at, data) VALUES (?, ?, ?)"
        if self._backend.engine.dialect.name == "postgresql":
            sql += " RETURNING id"
        result = self._backend._execute(sql, params)
        if self._backend.engine.dialect.name == "postgresql":
            row = result.fetchone()
            if row is None:
                raise BackendError("insert did not return id")
            new_id = int(row[0])
        else:
            new_id = int(result.lastrowid)
        data["id"] = new_id
        self._backend._execute(
            f"UPDATE {self._table} SET data = ? WHERE id = ?",
            (_dump(data), new_id),
        )
        return new_id


class _Result:
    def __init__(self, result: Any) -> None:
        self.lastrowid = getattr(result, "lastrowid", 0) or 0
        count = getattr(result, "rowcount", 0)
        self.rowcount = int(count) if count is not None and count >= 0 else 0
        self.rows = list(result.fetchall()) if result.returns_rows else []

    def fetchone(self) -> Any:
        return self.rows[0] if self.rows else None

    def fetchall(self) -> list[Any]:
        return self.rows


def _dump(data: Mapping[str, Any]) -> str:
    return json.dumps(data, default=_json_default)


def _json_default(value: Any) -> Any:
    if isinstance(value, datetime):
        return value.isoformat()
    raise TypeError(f"Object of type {type(value).__name__} is not JSON serializable")


def table_name(collection: str) -> str:
    name = collection.replace(".", "_")
    if not _IDENT.fullmatch(name):
        raise BackendError(f"invalid table name {name!r}")
    return name
