apiVersion: v1
kind: Service
metadata:
  name: magi-asp
  namespace: magi
  labels:
    app.kubernetes.io/name: magi-asp
spec:
  selector:
    app.kubernetes.io/name: magi-asp
  ports:
    - name: http
      port: 42069
      targetPort: http
