export { Bus, MAGI_CONTACT_ID, SYSTEM_CONTACT_ID } from "./bus.js";
export { BaseWorker } from "./baseWorker.js";
export type { Conversation } from "./firmware/books/conversationBook.js";
export type { Message } from "./firmware/books/messageBook.js";
export type { Memory, MemoryKind } from "./firmware/books/memoryBook.js";
export type { Skill } from "./firmware/books/skillsBook.js";
export type { Task } from "./firmware/books/taskBook.js";
export type { Contact, ContactRole } from "./firmware/books/contactBook.js";
export type { ContactNote, NoteKind } from "./firmware/books/contactNoteBook.js";
export type { McpConnectionType, McpServerConfig } from "./firmware/books/mcpServerBook.js";
export type { Setting } from "./firmware/books/settingsBook.js";
export type { ExecutableTool } from "./firmware/books/toolBook.js";
// One file per job; `types.js` is only the board contract that binds them.
export type { LLMToolCall, LLMMessage, LLMTool } from "./firmware/jobs/llm.js";
export type { ChatNotify } from "./firmware/jobs/chatNotify.js";
export type { CallLLMJob, CallLLMResult } from "./firmware/jobs/callLlm.js";
export type { RunToolJob, RunToolResult } from "./firmware/jobs/runTool.js";
export type { DeliveryNotify } from "./firmware/jobs/deliveryNotify.js";
export type { ChangeProviderNotify } from "./firmware/jobs/changeProvider.js";
export type { RunTaskNotify } from "./firmware/jobs/runTask.js";
export type { ChangeMcpServerNotify } from "./firmware/jobs/changeMcpServer.js";
export type { Job, JobResult } from "./firmware/jobs/types.js";
