export { Bus, MAGI_CONTACT_ID, SYSTEM_CONTACT_ID } from "./bus.js";
export { BaseWorker } from "./baseWorker.js";
export type { Conversation } from "./books/conversationBook.js";
export type { Message } from "./books/messageBook.js";
export type { Memory, MemoryKind } from "./books/memoryBook.js";
export type { Skill } from "./books/skillsBook.js";
export type { Task } from "./books/taskBook.js";
export type { Contact, ContactRole } from "./books/contactBook.js";
export type { ContactNote, NoteKind } from "./books/contactNoteBook.js";
export type { McpConnectionType, McpServerConfig } from "./books/mcpServerBook.js";
export type { Setting } from "./books/settingsBook.js";
export type { ExecutableTool, ToolSource } from "./books/toolBook.js";
// One file per job; `types.js` is only the board contract that binds them.
export type { LLMToolCall, LLMMessage, LLMTool } from "./jobs/llm.js";
export type { ChatNotify } from "./jobs/chatNotify.js";
export type { CallLLMJob, CallLLMResult } from "./jobs/callLlm.js";
export type { RunToolJob, RunToolResult } from "./jobs/runTool.js";
export type { DeliveryNotify } from "./jobs/deliveryNotify.js";
export type { ChangeProviderNotify } from "./jobs/changeProvider.js";
export type { RunTaskNotify } from "./jobs/runTask.js";
export type { ChangeMcpServerNotify } from "./jobs/changeMcpServer.js";
export type { ManageWorkerNotify } from "./jobs/manageWorker.js";
export type { Job, JobResult } from "./jobs/types.js";
